-- FLAME OFFICE: primeiro rascunho do esquema PostgreSQL.
-- Estrutura em revisão; não é uma migração de produção.
-- As tabelas iniciais foram criadas em um esquema de teste isolado no PostgreSQL 17.
-- O bloco financeiro ao final e um rascunho ainda nao executado.
-- Este arquivo não contém dados de negócio nem credenciais.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE TAB_CONFIG(
    ID_CONFIG SMALLINT PRIMARY KEY DEFAULT 1 CHECK (ID_CONFIG = 1), -- UMA CONFIGURACAO POR INSTALACAO
    VERSAO_ATUAL TEXT NOT NULL,
    DATA_ATUALIZACAO TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- ATUALIZAR AO ALTERAR A CONFIGURACAO
    STATUS_SISTEMA TEXT NOT NULL DEFAULT 'ATIVO'
        CHECK (STATUS_SISTEMA IN ('ATIVO', 'MANUTENCAO', 'BLOQUEADO')),
    CHAVE_LICENCA_HASH TEXT, -- HASH DA CHAVE; NUNCA ARMAZENAR A CHAVE EM TEXTO PURO
    STATUS_LICENCA TEXT NOT NULL DEFAULT 'PENDENTE'
        CHECK (STATUS_LICENCA IN ('PENDENTE', 'ATIVA', 'BLOQUEADA')),
    VALIDADE_LICENCA DATE,
    CHECK (STATUS_LICENCA <> 'ATIVA' OR
        (CHAVE_LICENCA_HASH IS NOT NULL AND VALIDADE_LICENCA IS NOT NULL))
);

-- CHAMADA: CALL PROC_VERIFICAR_LICENCA(NULL, NULL, NULL, NULL);
CREATE OR REPLACE PROCEDURE PROC_VERIFICAR_LICENCA(
    OUT SUCESSO BOOLEAN,
    OUT RETORNO TEXT,
    OUT VALIDADE DATE,
    OUT MSG TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_STATUS_SISTEMA TEXT;
    V_STATUS_LICENCA TEXT;
BEGIN
    SELECT C.STATUS_SISTEMA, C.STATUS_LICENCA, C.VALIDADE_LICENCA
    INTO V_STATUS_SISTEMA, V_STATUS_LICENCA, VALIDADE
    FROM TAB_CONFIG C
    WHERE C.ID_CONFIG = 1;

    SUCESSO := FALSE;

    IF NOT FOUND THEN
        RETORNO := 'CONFIG_AUSENTE';
        MSG := 'Configuracao do sistema nao encontrada.';
    ELSIF V_STATUS_SISTEMA = 'BLOQUEADO' THEN
        RETORNO := 'SISTEMA_BLOQUEADO';
        MSG := 'O sistema esta bloqueado.';
    ELSIF V_STATUS_SISTEMA = 'MANUTENCAO' THEN
        RETORNO := 'SISTEMA_EM_MANUTENCAO';
        MSG := 'O sistema esta em manutencao.';
    ELSIF V_STATUS_LICENCA = 'PENDENTE' THEN
        RETORNO := 'LICENCA_PENDENTE';
        MSG := 'A licenca ainda nao foi ativada.';
    ELSIF V_STATUS_LICENCA = 'BLOQUEADA' THEN
        RETORNO := 'LICENCA_BLOQUEADA';
        MSG := 'A licenca esta bloqueada.';
    ELSIF VALIDADE IS NULL THEN
        RETORNO := 'LICENCA_SEM_VALIDADE';
        MSG := 'A licenca nao tem data de validade.';
    ELSIF CURRENT_DATE > VALIDADE THEN
        RETORNO := 'LICENCA_EXPIRADA';
        MSG := 'A licenca expirou em ' || TO_CHAR(VALIDADE, 'DD/MM/YYYY') || '.';
    ELSE
        SUCESSO := TRUE;
        RETORNO := 'OK';
        MSG := 'Licenca valida.';
    END IF;
END;
$$;

CREATE TABLE TAB_UNIDADES_MEDIDA(
    SIGLA TEXT PRIMARY KEY,
    GRANDEZA TEXT NOT NULL CHECK (GRANDEZA IN ('MASSA', 'VOLUME', 'CONTAGEM', 'EMBALAGEM')),
    FATOR_BASE NUMERIC(18,6), -- G, ML E UN SAO AS UNIDADES BASE
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (FATOR_BASE IS NULL OR FATOR_BASE > 0),
    CHECK ((GRANDEZA = 'EMBALAGEM') = (FATOR_BASE IS NULL))
);

-- DADOS DE REFERENCIA; EMBALAGENS COMO CX USAM A QUANTIDADE INFORMADA NO INSUMO.
INSERT INTO TAB_UNIDADES_MEDIDA (SIGLA, GRANDEZA, FATOR_BASE) VALUES
    ('G', 'MASSA', 1),
    ('KG', 'MASSA', 1000),
    ('ML', 'VOLUME', 1),
    ('L', 'VOLUME', 1000),
    ('UN', 'CONTAGEM', 1),
    ('CX', 'EMBALAGEM', NULL);

CREATE OR REPLACE FUNCTION FN_GTIN_VALIDO(P_GTIN TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    V_SOMA INT := 0;
    V_POS INT;
    V_TAMANHO INT;
BEGIN
    IF P_GTIN IS NULL OR P_GTIN !~ '^[0-9]+$'
        OR LENGTH(P_GTIN) NOT IN (8, 12, 13, 14) THEN
        RETURN FALSE;
    END IF;

    V_TAMANHO := LENGTH(P_GTIN);
    FOR V_POS IN 1..V_TAMANHO - 1 LOOP
        V_SOMA := V_SOMA + SUBSTRING(P_GTIN FROM V_POS FOR 1)::INT
            * CASE WHEN (V_TAMANHO - V_POS) % 2 = 1 THEN 3 ELSE 1 END;
    END LOOP;

    RETURN (10 - V_SOMA % 10) % 10 = RIGHT(P_GTIN, 1)::INT;
END;
$$;

CREATE TABLE TAB_INSUMOS(
    ID_INSUMO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COD_EXTERNO TEXT, -- CODIGO DA NOTA DE COMPRA
    EAN TEXT UNIQUE CHECK (EAN IS NULL OR FN_GTIN_VALIDO(EAN)),
    DESCRICAO TEXT NOT NULL,
    UM_COMPRA TEXT NOT NULL, -- UNIDADE INDICATIVA DE COMPRA
    UM_VENDA TEXT NOT NULL, -- UNIDADE INDICATIVA DE CONSUMO
    QTDE_COMPRA NUMERIC(14,3) NOT NULL CHECK (QTDE_COMPRA > 0), -- CONTEUDO DE UMA EMBALAGEM NA ESCALA DO ESTOQUE
    QTDE_VENDA NUMERIC(14,3) NOT NULL CHECK (QTDE_VENDA > 0), -- QUANTIDADE CONSUMIDA POR PORCAO NA MESMA ESCALA
    CUSTO NUMERIC (10,2) NOT NULL CHECK (CUSTO >= 0), -- CUSTO DE UMA EMBALAGEM
    CUSTO_MEDIO NUMERIC (10,2) NOT NULL DEFAULT 0, -- ATUALIZADO NA ENTRADA
    CUSTO_UNITARIO NUMERIC (14,6) NOT NULL CHECK (CUSTO_UNITARIO >= 0), -- CUSTO DE UMA PORCAO
    CATEGORIA TEXT,
    MARCA TEXT,
    -- ESTOQUE VEM CALCULADO PELO MOV ESTOQUE
    ESTOQUE_MINIMO NUMERIC (14,3) NOT NULL CHECK (ESTOQUE_MINIMO >= 0),
    ESTOQUE_RECOMENDADO NUMERIC (14,3) NOT NULL CHECK (ESTOQUE_RECOMENDADO >= ESTOQUE_MINIMO),
    STATUS TEXT,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE TAB_INSUMOS ADD CONSTRAINT FK_INSUMO_UM_COMPRA
FOREIGN KEY (UM_COMPRA) REFERENCES TAB_UNIDADES_MEDIDA(SIGLA);

ALTER TABLE TAB_INSUMOS ADD CONSTRAINT FK_INSUMO_UM_VENDA
FOREIGN KEY (UM_VENDA) REFERENCES TAB_UNIDADES_MEDIDA(SIGLA);

CREATE TABLE TAB_FORNECEDORES(
    ID_FORNECEDOR INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CNPJ TEXT NOT NULL UNIQUE,
    RAZAO_SOCIAL TEXT NOT NULL,
    FANTASIA TEXT,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE TAB_FORNECEDOR_INSUMOS(
    ID_FORNECEDOR_INSUMO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL REFERENCES TAB_FORNECEDORES(ID_FORNECEDOR),
    ID_INSUMO INT NOT NULL REFERENCES TAB_INSUMOS(ID_INSUMO),
    CODIGO_FORNECEDOR TEXT NOT NULL CHECK (LENGTH(BTRIM(CODIGO_FORNECEDOR)) BETWEEN 1 AND 80),
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (ID_FORNECEDOR, CODIGO_FORNECEDOR)
);

-- CADASTRA ITEM DE ESTOQUE. UNIDADES SAO INDICATIVAS; AS QUANTIDADES SAO INFORMADAS MANUALMENTE.
-- EX.: PACOTE DE 1,5 KG: QTDE_COMPRA = 1500 G E QTDE_VENDA = 30 G POR PORCAO.
-- CUSTO_UNITARIO = CUSTO / QTDE_COMPRA * QTDE_VENDA. O CADASTRO NAO CRIA SALDO.
CREATE OR REPLACE PROCEDURE PROC_CADASTRAR_INSUMO(
    IN P_DESCRICAO TEXT,
    IN P_EAN TEXT,
    IN P_UM_COMPRA TEXT,
    IN P_QTDE_COMPRA NUMERIC,
    IN P_UM_VENDA TEXT,
    IN P_QTDE_VENDA NUMERIC,
    IN P_CUSTO TEXT,
    IN P_ESTOQUE_MINIMO NUMERIC,
    IN P_ESTOQUE_RECOMENDADO NUMERIC,
    IN P_CATEGORIA TEXT,
    IN P_MARCA TEXT,
    IN P_STATUS TEXT,
    IN P_ID_FORNECEDOR INT,
    IN P_CODIGO_FORNECEDOR TEXT,
    OUT SUCESSO BOOLEAN,
    OUT RETORNO TEXT,
    OUT MSG TEXT,
    OUT ID_INSUMO INT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_EAN TEXT := NULLIF(BTRIM(P_EAN), '');
    V_CODIGO_FORNECEDOR TEXT := NULLIF(BTRIM(P_CODIGO_FORNECEDOR), '');
    V_UM_COMPRA TEXT := UPPER(BTRIM(P_UM_COMPRA));
    V_UM_VENDA TEXT := UPPER(BTRIM(P_UM_VENDA));
    V_STATUS TEXT := COALESCE(UPPER(BTRIM(P_STATUS)), 'ATIVO');
    V_CUSTO_TEXTO TEXT := BTRIM(P_CUSTO);
    V_CUSTO NUMERIC;
    V_CUSTO_UNITARIO NUMERIC;
BEGIN
    SUCESSO := FALSE;
    ID_INSUMO := NULL;

    IF P_DESCRICAO IS NULL OR LENGTH(BTRIM(P_DESCRICAO)) NOT BETWEEN 1 AND 80
        OR P_DESCRICAO ~ '[[:cntrl:]]' THEN
        RETORNO := 'DESCRICAO_INVALIDA';
        MSG := 'Informe uma descricao de ate 80 caracteres, sem caracteres de controle.';
        RETURN;
    END IF;

    IF V_EAN IS NOT NULL AND NOT FN_GTIN_VALIDO(V_EAN) THEN
        RETORNO := 'EAN_INVALIDO';
        MSG := 'EAN/GTIN deve ter 8, 12, 13 ou 14 digitos e digito verificador valido.';
        RETURN;
    END IF;

    IF V_EAN IS NOT NULL AND EXISTS (SELECT 1 FROM TAB_INSUMOS WHERE EAN = V_EAN) THEN
        RETORNO := 'EAN_DUPLICADO';
        MSG := 'EAN/GTIN ja cadastrado.';
        RETURN;
    END IF;

    IF P_QTDE_COMPRA IS NULL OR P_QTDE_COMPRA <= 0 OR P_QTDE_COMPRA >= 100000000000
        OR P_QTDE_COMPRA <> ROUND(P_QTDE_COMPRA, 3)
        OR P_QTDE_VENDA IS NULL OR P_QTDE_VENDA <= 0 OR P_QTDE_VENDA >= 100000000000
        OR P_QTDE_VENDA <> ROUND(P_QTDE_VENDA, 3) THEN
        RETORNO := 'QUANTIDADE_INVALIDA';
        MSG := 'Quantidades devem ser positivas e ter no maximo tres casas decimais.';
        RETURN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM TAB_UNIDADES_MEDIDA
        WHERE SIGLA = V_UM_COMPRA AND NOT EXCLUIDO) THEN
        RETORNO := 'UNIDADE_COMPRA_INVALIDA';
        MSG := 'Unidade de compra nao cadastrada.';
        RETURN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM TAB_UNIDADES_MEDIDA
        WHERE SIGLA = V_UM_VENDA AND NOT EXCLUIDO) THEN
        RETORNO := 'UNIDADE_VENDA_INVALIDA';
        MSG := 'Unidade de consumo nao cadastrada.';
        RETURN;
    END IF;

    IF V_CUSTO_TEXTO IS NULL OR V_CUSTO_TEXTO !~ '^[0-9]{1,8}([.,][0-9]{1,2})?$' THEN
        RETORNO := 'CUSTO_INVALIDO';
        MSG := 'Custo deve ter no maximo duas casas decimais, sem separador de milhar.';
        RETURN;
    END IF;
    V_CUSTO := REPLACE(V_CUSTO_TEXTO, ',', '.')::NUMERIC;
    V_CUSTO_UNITARIO := ROUND(V_CUSTO / P_QTDE_COMPRA * P_QTDE_VENDA, 6);
    IF V_CUSTO_UNITARIO >= 100000000 THEN
        RETORNO := 'CUSTO_UNITARIO_INVALIDO';
        MSG := 'Custo da porcao excede o limite do campo.';
        RETURN;
    END IF;

    IF P_ESTOQUE_MINIMO IS NULL OR P_ESTOQUE_MINIMO < 0
        OR P_ESTOQUE_MINIMO >= 100000000000
        OR P_ESTOQUE_MINIMO <> ROUND(P_ESTOQUE_MINIMO, 3)
        OR P_ESTOQUE_RECOMENDADO IS NULL OR P_ESTOQUE_RECOMENDADO < P_ESTOQUE_MINIMO
        OR P_ESTOQUE_RECOMENDADO >= 100000000000
        OR P_ESTOQUE_RECOMENDADO <> ROUND(P_ESTOQUE_RECOMENDADO, 3) THEN
        RETORNO := 'ESTOQUE_ALVO_INVALIDO';
        MSG := 'Estoque recomendado deve ser maior ou igual ao minimo, com ate tres casas.';
        RETURN;
    END IF;

    IF V_STATUS NOT IN ('ATIVO', 'INATIVO') THEN
        RETORNO := 'STATUS_INVALIDO';
        MSG := 'Status deve ser ATIVO ou INATIVO.';
        RETURN;
    END IF;

    IF (P_CATEGORIA IS NOT NULL AND LENGTH(BTRIM(P_CATEGORIA)) > 80)
        OR (P_MARCA IS NOT NULL AND LENGTH(BTRIM(P_MARCA)) > 80) THEN
        RETORNO := 'TEXTO_LONGO';
        MSG := 'Categoria e marca devem ter ate 80 caracteres.';
        RETURN;
    END IF;

    IF (P_ID_FORNECEDOR IS NULL) <> (V_CODIGO_FORNECEDOR IS NULL)
        OR (V_CODIGO_FORNECEDOR IS NOT NULL AND
            (LENGTH(V_CODIGO_FORNECEDOR) > 80 OR V_CODIGO_FORNECEDOR ~ '[[:cntrl:]]')) THEN
        RETORNO := 'CODIGO_FORNECEDOR_INVALIDO';
        MSG := 'Informe fornecedor e codigo juntos; codigo deve ter ate 80 caracteres.';
        RETURN;
    END IF;

    IF P_ID_FORNECEDOR IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM TAB_FORNECEDORES
            WHERE ID_FORNECEDOR = P_ID_FORNECEDOR AND NOT EXCLUIDO) THEN
            RETORNO := 'FORNECEDOR_INVALIDO';
            MSG := 'Fornecedor nao cadastrado ou excluido.';
            RETURN;
        END IF;
        IF EXISTS (SELECT 1 FROM TAB_FORNECEDOR_INSUMOS
            WHERE ID_FORNECEDOR = P_ID_FORNECEDOR
                AND CODIGO_FORNECEDOR = V_CODIGO_FORNECEDOR) THEN
            RETORNO := 'CODIGO_FORNECEDOR_DUPLICADO';
            MSG := 'Codigo ja utilizado por este fornecedor.';
            RETURN;
        END IF;
    END IF;

    INSERT INTO TAB_INSUMOS (
        EAN, DESCRICAO, UM_COMPRA, UM_VENDA, QTDE_COMPRA, QTDE_VENDA,
        CUSTO, CUSTO_MEDIO, CUSTO_UNITARIO, CATEGORIA, MARCA,
        ESTOQUE_MINIMO, ESTOQUE_RECOMENDADO, STATUS
    ) VALUES (
        V_EAN, BTRIM(P_DESCRICAO), V_UM_COMPRA, V_UM_VENDA, P_QTDE_COMPRA, P_QTDE_VENDA,
        V_CUSTO, 0, V_CUSTO_UNITARIO,
        NULLIF(BTRIM(P_CATEGORIA), ''), NULLIF(BTRIM(P_MARCA), ''),
        P_ESTOQUE_MINIMO, P_ESTOQUE_RECOMENDADO, V_STATUS
    ) RETURNING TAB_INSUMOS.ID_INSUMO INTO ID_INSUMO;

    IF P_ID_FORNECEDOR IS NOT NULL THEN
        INSERT INTO TAB_FORNECEDOR_INSUMOS (ID_FORNECEDOR, ID_INSUMO, CODIGO_FORNECEDOR)
        VALUES (P_ID_FORNECEDOR, ID_INSUMO, V_CODIGO_FORNECEDOR);
    END IF;

    SUCESSO := TRUE;
    RETORNO := 'OK';
    MSG := 'Insumo cadastrado com sucesso.';
END;
$$;

CREATE TABLE TAB_USUARIOS(
    ID_USUARIO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME TEXT NOT NULL CHECK (LENGTH(BTRIM(NOME)) BETWEEN 1 AND 80),
    LOGIN TEXT NOT NULL UNIQUE CHECK (LENGTH(LOGIN) BETWEEN 3 AND 40),
    SENHA_HASH TEXT NOT NULL, -- GERAR COM CRYPT(SENHA, GEN_SALT('bf')); SENHA DE ATE 72 BYTES
    SETOR TEXT NOT NULL CHECK (SETOR IN ('FINANCEIRO', 'ESTOQUE', 'MARKETING', 'GERAL')),
    STATUS TEXT NOT NULL DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'INATIVO')),
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX UQ_USUARIOS_LOGIN_CI ON TAB_USUARIOS (UPPER(LOGIN));

CREATE OR REPLACE PROCEDURE PROC_CADASTRAR_USUARIO(
    IN P_NOME TEXT,
    IN P_LOGIN TEXT,
    IN P_SENHA TEXT,
    IN P_SETOR TEXT,
    IN P_STATUS TEXT,
    OUT SUCESSO BOOLEAN,
    OUT RETORNO TEXT,
    OUT MSG TEXT,
    OUT ID_USUARIO INT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_LOGIN TEXT := UPPER(BTRIM(P_LOGIN));
    V_SETOR TEXT := UPPER(BTRIM(P_SETOR));
    V_STATUS TEXT := COALESCE(UPPER(BTRIM(P_STATUS)), 'ATIVO');
BEGIN
    SUCESSO := FALSE;
    ID_USUARIO := NULL;

    IF P_NOME IS NULL OR LENGTH(BTRIM(P_NOME)) NOT BETWEEN 1 AND 80
        OR P_NOME ~ '[[:cntrl:]]' THEN
        RETORNO := 'NOME_INVALIDO';
        MSG := 'Nome deve ter de 1 a 80 caracteres, sem caracteres de controle.';
        RETURN;
    END IF;

    IF V_LOGIN IS NULL OR LENGTH(V_LOGIN) NOT BETWEEN 3 AND 40
        OR V_LOGIN !~ '^[A-Z0-9._@-]+$' THEN
        RETORNO := 'LOGIN_INVALIDO';
        MSG := 'Login deve ter de 3 a 40 caracteres e conter apenas letras, numeros, ponto, arroba, hifen ou sublinhado.';
        RETURN;
    END IF;

    IF EXISTS (SELECT 1 FROM TAB_USUARIOS WHERE UPPER(LOGIN) = V_LOGIN) THEN
        RETORNO := 'LOGIN_DUPLICADO';
        MSG := 'Login ja cadastrado.';
        RETURN;
    END IF;

    IF P_SENHA IS NULL OR OCTET_LENGTH(P_SENHA) NOT BETWEEN 4 AND 72
        OR BTRIM(P_SENHA) = '' OR P_SENHA ~ '[[:cntrl:]]' THEN
        RETORNO := 'SENHA_INVALIDA';
        MSG := 'Senha deve ter de 4 a 72 bytes e nao pode ser vazia ou conter caracteres de controle.';
        RETURN;
    END IF;

    IF V_SETOR IS NULL OR V_SETOR NOT IN ('FINANCEIRO', 'ESTOQUE', 'MARKETING', 'GERAL') THEN
        RETORNO := 'SETOR_INVALIDO';
        MSG := 'Setor invalido.';
        RETURN;
    END IF;

    IF V_STATUS NOT IN ('ATIVO', 'INATIVO') THEN
        RETORNO := 'STATUS_INVALIDO';
        MSG := 'Status deve ser ATIVO ou INATIVO.';
        RETURN;
    END IF;

    INSERT INTO TAB_USUARIOS (NOME, LOGIN, SENHA_HASH, SETOR, STATUS)
    VALUES (BTRIM(P_NOME), V_LOGIN, CRYPT(P_SENHA, GEN_SALT('bf')), V_SETOR, V_STATUS)
    RETURNING TAB_USUARIOS.ID_USUARIO INTO ID_USUARIO;

    SUCESSO := TRUE;
    RETORNO := 'OK';
    MSG := 'Usuario cadastrado com sucesso.';
EXCEPTION
    WHEN unique_violation THEN
        SUCESSO := FALSE;
        ID_USUARIO := NULL;
        RETORNO := 'LOGIN_DUPLICADO';
        MSG := 'Login ja cadastrado.';
END;
$$;

-- CHAMADA: CALL PROC_LOGIN('login', 'senha', NULL, NULL, NULL, NULL);
CREATE OR REPLACE PROCEDURE PROC_LOGIN(
    IN P_USUARIO TEXT,
    IN P_SENHA TEXT,
    OUT RETORNO TEXT,
    OUT ID_USUARIO INT,
    OUT USUARIO TEXT,
    OUT SETOR TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_ID_USUARIO INT;
    V_USUARIO TEXT;
    V_SETOR TEXT;
    V_STATUS TEXT;
    V_SENHA_HASH TEXT;
    V_LIBERAUSUARIO SMALLINT := 0;
    V_LIBERASENHA SMALLINT := 0;
BEGIN
    ID_USUARIO := NULL;
    USUARIO := NULL;
    SETOR := NULL;

    SELECT U.ID_USUARIO, U.LOGIN, U.SETOR, U.STATUS
    INTO V_ID_USUARIO, V_USUARIO, V_SETOR, V_STATUS
    FROM TAB_USUARIOS U
    WHERE UPPER(U.LOGIN) = UPPER(BTRIM(P_USUARIO))
        AND NOT U.EXCLUIDO;

    IF FOUND THEN
        V_LIBERAUSUARIO := 1;
    END IF;

    SELECT U.SENHA_HASH INTO V_SENHA_HASH
    FROM TAB_USUARIOS U
    WHERE U.ID_USUARIO = V_ID_USUARIO
        AND OCTET_LENGTH(P_SENHA) <= 72
        AND U.SENHA_HASH = CRYPT(P_SENHA, U.SENHA_HASH);

    IF FOUND THEN
        V_LIBERASENHA := 1;
    END IF;

    IF V_LIBERAUSUARIO = 0 AND V_LIBERASENHA = 0 THEN
        RETORNO := 'USUARIO_INVALIDO';
        RETURN;
    ELSIF V_LIBERAUSUARIO = 0 AND V_LIBERASENHA = 1 THEN
        RETORNO := 'USUARIO_OU_SENHA_INVALIDOS';
        RETURN;
    ELSIF V_LIBERAUSUARIO = 1 AND V_LIBERASENHA = 0 THEN
        RETORNO := 'SENHA_INVALIDA';
        RETURN;
    END IF;

    IF V_STATUS = 'INATIVO' THEN
        RETORNO := 'USUARIO_INATIVO';
        RETURN;
    END IF;

    RETORNO := 'OK';
    ID_USUARIO := V_ID_USUARIO;
    USUARIO := V_USUARIO;
    SETOR := V_SETOR;
END;
$$;

CREATE TABLE TAB_MOVIMENTO_ESTOQUE(
    ID_MOVIMENTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_INSUMO INT NOT NULL,
    ID_ORIGEM INT,
    QTDE NUMERIC(14,3) NOT NULL,
    ESTOQUE_ANTERIOR NUMERIC(14,3),
    ESTOQUE_POSTERIOR NUMERIC(14,3),
    CUSTO_UNITARIO NUMERIC(10,2) NOT NULL,
    CUSTO_TOTAL NUMERIC(10,2),
    DATA_MOVIMENTO TIMESTAMPTZ DEFAULT NOW(),
    TIPO_MOVIMENTO TEXT,
    MOTIVO_MOVIMENTO TEXT,
    ID_LOJA INT NOT NULL,
    ID_USUARIO INT NOT NULL
);

ALTER TABLE TAB_MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_INSUMO_MOVIMENTO
FOREIGN KEY (ID_INSUMO) REFERENCES TAB_INSUMOS(ID_INSUMO);

ALTER TABLE TAB_MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_USUARIO_MOVIMENTO
FOREIGN KEY (ID_USUARIO) REFERENCES TAB_USUARIOS(ID_USUARIO);

CREATE TABLE TAB_ENTRADAS(
    ID_ENTRADA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL,
    CHAVE_NFE TEXT UNIQUE,
    NUMERO_NFE TEXT,
    VALOR_TOTAL NUMERIC(10,2),
    DATA_ENTRADA TIMESTAMPTZ DEFAULT NOW(),
    STATUS TEXT
);

ALTER TABLE TAB_ENTRADAS ADD CONSTRAINT FK_FORNECEDOR_ENTRADA
FOREIGN KEY (ID_FORNECEDOR) REFERENCES TAB_FORNECEDORES(ID_FORNECEDOR);

CREATE TABLE TAB_ENTRADA_ITENS(
    ID_ITEM BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ENTRADA INT NOT NULL,
    ID_INSUMO INT NOT NULL,
    QTDE_NFE NUMERIC(14,3) NOT NULL,
    UM_COMPRA TEXT,
    UM_ENTRADA TEXT,
    FATOR_CONVERSAO NUMERIC(18,6), -- DEPENDE DA UM_ENTRADA
    QTDE_ENTRADA NUMERIC(14,3) NOT NULL,
    CUSTO_UNITARIO NUMERIC(10,2) NOT NULL,
    SUBTOTAL NUMERIC(10,2) NOT NULL
);

ALTER TABLE TAB_ENTRADA_ITENS ADD CONSTRAINT FK_ENTRADA_INSUMO
FOREIGN KEY (ID_INSUMO) REFERENCES TAB_INSUMOS(ID_INSUMO);

ALTER TABLE TAB_ENTRADA_ITENS ADD CONSTRAINT FK_IDITEM_IDENTRADA
FOREIGN KEY (ID_ENTRADA) REFERENCES TAB_ENTRADAS(ID_ENTRADA);

CREATE TABLE TAB_PRODUTOS ( -- PRODUTO FINAL INDIVIDUAL: LANCHE, PORÇÃO ETC
    ID_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO TEXT UNIQUE NOT NULL CHECK (LENGTH(BTRIM(DESCRICAO)) BETWEEN 1 AND 80),
    CATEGORIA TEXT,
    CMV NUMERIC(10,2),
    PRECO_VENDA NUMERIC(10,2) NOT NULL CHECK (PRECO_VENDA > 0),
    STATUS TEXT NOT NULL DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'INATIVO')),
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

-- PRODUTO VENDAVEL: INSUMOS, QUANTIDADES E CONVERSOES SAO CADASTRADOS SEPARADAMENTE.
CREATE OR REPLACE PROCEDURE PROC_CADASTRAR_PRODUTO(
    IN P_DESCRICAO TEXT,
    IN P_CATEGORIA TEXT,
    IN P_PRECO_VENDA TEXT,
    IN P_STATUS TEXT,
    OUT SUCESSO BOOLEAN,
    OUT RETORNO TEXT,
    OUT MSG TEXT,
    OUT ID_PRODUTO INT
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_PRECO_TEXTO TEXT := BTRIM(P_PRECO_VENDA);
    V_PRECO NUMERIC;
    V_STATUS TEXT := COALESCE(UPPER(BTRIM(P_STATUS)), 'ATIVO');
BEGIN
    SUCESSO := FALSE;
    ID_PRODUTO := NULL;

    IF P_DESCRICAO IS NULL OR LENGTH(BTRIM(P_DESCRICAO)) NOT BETWEEN 1 AND 80
        OR P_DESCRICAO ~ '[[:cntrl:]]' THEN
        RETORNO := 'DESCRICAO_INVALIDA';
        MSG := 'Informe uma descricao de ate 80 caracteres, sem caracteres de controle.';
        RETURN;
    END IF;

    IF EXISTS (SELECT 1 FROM TAB_PRODUTOS
        WHERE LOWER(BTRIM(DESCRICAO)) = LOWER(BTRIM(P_DESCRICAO))) THEN
        RETORNO := 'PRODUTO_DUPLICADO';
        MSG := 'Produto ja cadastrado.';
        RETURN;
    END IF;

    IF P_CATEGORIA IS NOT NULL AND LENGTH(BTRIM(P_CATEGORIA)) > 80 THEN
        RETORNO := 'CATEGORIA_INVALIDA';
        MSG := 'Categoria deve ter ate 80 caracteres.';
        RETURN;
    END IF;

    IF V_PRECO_TEXTO IS NULL OR V_PRECO_TEXTO !~ '^[0-9]{1,8}([.,][0-9]{1,2})?$' THEN
        RETORNO := 'PRECO_INVALIDO';
        MSG := 'Preco deve ter no maximo duas casas decimais, sem separador de milhar.';
        RETURN;
    END IF;
    V_PRECO := REPLACE(V_PRECO_TEXTO, ',', '.')::NUMERIC;
    IF V_PRECO <= 0 THEN
        RETORNO := 'PRECO_INVALIDO';
        MSG := 'Preco deve ser maior que zero.';
        RETURN;
    END IF;

    IF V_STATUS NOT IN ('ATIVO', 'INATIVO') THEN
        RETORNO := 'STATUS_INVALIDO';
        MSG := 'Status deve ser ATIVO ou INATIVO.';
        RETURN;
    END IF;

    INSERT INTO TAB_PRODUTOS (DESCRICAO, CATEGORIA, PRECO_VENDA, STATUS)
    VALUES (BTRIM(P_DESCRICAO), NULLIF(BTRIM(P_CATEGORIA), ''), V_PRECO, V_STATUS)
    RETURNING TAB_PRODUTOS.ID_PRODUTO INTO ID_PRODUTO;

    SUCESSO := TRUE;
    RETORNO := 'OK';
    MSG := 'Produto cadastrado com sucesso.';
END;
$$;

CREATE TABLE TAB_PRODUTO_INSUMOS ( -- COMPONENTES DOS PRODUTOS
    ID_INSUMO_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- ID LINHA
    ID_PRODUTO INT NOT NULL, -- ID PRODUTO FINAL
    ID_INSUMO INT NOT NULL, -- ID INSUMO
    QTDE_VENDA NUMERIC(14,3),
    FATOR_USO NUMERIC(10,2),
    CUSTO_UNITARIO NUMERIC (10,2),
    SUBTOTAL NUMERIC (10,2),
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE TAB_PRODUTO_INSUMOS ADD CONSTRAINT FK_PRODUTO_INSUMO
FOREIGN KEY (ID_INSUMO) REFERENCES TAB_INSUMOS(ID_INSUMO);

ALTER TABLE TAB_PRODUTO_INSUMOS ADD CONSTRAINT FK_PRODUTO_IDPRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

CREATE TABLE TAB_COMBOS ( -- COMBOS DE PRODUTOS
    ID_COMBO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO TEXT UNIQUE NOT NULL,
    CMV_COMBO NUMERIC(10,2),
    PRECO_VENDA NUMERIC(10,2),
    STATUS TEXT,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE TAB_COMBO_PRODUTOS(
    ID_COMBO_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMBO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTDE NUMERIC(14,3) NOT NULL,
    CMV NUMERIC(10,2),
    SUBTOTAL NUMERIC(10,2),
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE TAB_COMBO_PRODUTOS ADD CONSTRAINT FK_COMBO_IDCOMBO
FOREIGN KEY (ID_COMBO) REFERENCES TAB_COMBOS(ID_COMBO);

ALTER TABLE TAB_COMBO_PRODUTOS ADD CONSTRAINT FK_COMBO_PRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

CREATE TABLE TAB_LOJAS(
    ID_LOJA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_LOJA TEXT NOT NULL UNIQUE,
    CATEGORIA TEXT,
    STATUS TEXT,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE TAB_LOJAS_PLATAFORMAS(
    ID_LOJA_PLATAFORMA TEXT PRIMARY KEY,
    ID_LOJA INT NOT NULL,
    PLATAFORMA TEXT,
    STATUS TEXT,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE TAB_LOJAS_PLATAFORMAS ADD CONSTRAINT FK_LOJA_IDLOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

ALTER TABLE TAB_MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_MOVIMENTO_LOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

CREATE TABLE TAB_VENDAS(
    ID_VENDA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA_PLATAFORMA TEXT NOT NULL,
    ID_LOJA INT NOT NULL,
    ID_LOJA_PLATAFORMA TEXT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    HORA_VENDA TIME NOT NULL,
    CUSTO_VENDA NUMERIC(10,2) NOT NULL DEFAULT 0,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL DEFAULT 0,
    DESCONTO_PLATAFORMA NUMERIC(10,2) DEFAULT 0,
    DESCONTO_PAGAMENTO NUMERIC(10,2) DEFAULT 0,
    DESCONTO_ENTREGA NUMERIC(10,2) DEFAULT 0,
    DESCONTO_PROMOCAO NUMERIC(10,2) DEFAULT 0,
    DESCONTO_TOTAL NUMERIC(10,2) DEFAULT 0,
    LUCRO_BRUTO NUMERIC (10,2) DEFAULT 0,
    MARGEM_BRUTA NUMERIC (10,2) DEFAULT 0,
    MARKUP_BRUTO NUMERIC(10,2) DEFAULT 0,
    STATUS TEXT
);

ALTER TABLE TAB_VENDAS ADD CONSTRAINT FK_VENDA_LOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

ALTER TABLE TAB_VENDAS ADD CONSTRAINT FK_VENDA_PLATAFORMA
FOREIGN KEY (ID_LOJA_PLATAFORMA) REFERENCES TAB_LOJAS_PLATAFORMAS(ID_LOJA_PLATAFORMA);

CREATE TABLE TAB_VENDAS_PRODUTOS(
    ID_VENDA_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTDE NUMERIC (14,3) NOT NULL,
    CUSTO NUMERIC (10,2) NOT NULL DEFAULT 0,
    SUBTOTAL NUMERIC(10,2) DEFAULT 0
);

ALTER TABLE TAB_VENDAS_PRODUTOS ADD CONSTRAINT FK_VENDAPRODUTO_IDVENDA
FOREIGN KEY (ID_VENDA) REFERENCES TAB_VENDAS(ID_VENDA);

ALTER TABLE TAB_VENDAS_PRODUTOS ADD CONSTRAINT FK_VENDAPRODUTO_IDPRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

CREATE TABLE TAB_VENDAS_COMPONENTES(
    ID_COMPONENTE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA INT NOT NULL,
    ID_COMBO INT,
    ID_PRODUTO INT,
    QTDE NUMERIC (14,3),
    CUSTO NUMERIC (10,2),
    SUBTOTAL NUMERIC(10,2)
);

ALTER TABLE TAB_VENDAS_COMPONENTES ADD CONSTRAINT FK_COMPONENTE_IDVENDA
FOREIGN KEY (ID_VENDA) REFERENCES TAB_VENDAS(ID_VENDA);

ALTER TABLE TAB_VENDAS_COMPONENTES ADD CONSTRAINT FK_COMPONENTE_IDCOMBO
FOREIGN KEY (ID_COMBO) REFERENCES TAB_COMBOS(ID_COMBO);

ALTER TABLE TAB_VENDAS_COMPONENTES ADD CONSTRAINT FK_COMPONENTE_IDPRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

-- FINANCEIRO (RASCUNHO): ORIGEM DO TITULO, REPASSE E EXTRATO SAO FATOS DIFERENTES.
-- PENDENTE: RELACIONAR LOJAS E CONTAS BANCARIAS AO CNPJ QUANDO TAB_EMPRESAS FOR DEFINIDA.

CREATE TABLE TAB_CONTAS_A_PAGAR(
    ID_CONTA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_LOJA INT NOT NULL,
    ID_ENTRADA INT UNIQUE, -- PREENCHIDO QUANDO A CONTA NASCE DE UMA NF/ENTRADA
    ORIGEM TEXT NOT NULL CHECK (ORIGEM IN ('NF_ENTRADA', 'MANUAL')),
    BENEFICIARIO TEXT, -- USADO QUANDO NAO HA FORNECEDOR CADASTRADO
    DESCRICAO TEXT NOT NULL,
    CATEGORIA TEXT,
    COMPETENCIA DATE,
    VALOR_TOTAL NUMERIC(12,2) NOT NULL CHECK (VALOR_TOTAL >= 0),
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW(),
    CHECK ((ORIGEM = 'NF_ENTRADA' AND ID_ENTRADA IS NOT NULL)
        OR (ORIGEM = 'MANUAL' AND ID_ENTRADA IS NULL))
);

ALTER TABLE TAB_CONTAS_A_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_LOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

ALTER TABLE TAB_CONTAS_A_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_ENTRADA
FOREIGN KEY (ID_ENTRADA) REFERENCES TAB_ENTRADAS(ID_ENTRADA);

CREATE TABLE TAB_PARCELAS_A_PAGAR(
    ID_PARCELA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    NUMERO_PARCELA INT NOT NULL CHECK (NUMERO_PARCELA > 0),
    VENCIMENTO DATE NOT NULL,
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    UNIQUE (ID_CONTA, NUMERO_PARCELA)
);

ALTER TABLE TAB_PARCELAS_A_PAGAR ADD CONSTRAINT FK_PARCELA_PAGAR_CONTA
FOREIGN KEY (ID_CONTA) REFERENCES TAB_CONTAS_A_PAGAR(ID_CONTA);

CREATE TABLE TAB_CONTAS_A_RECEBER(
    ID_CONTA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA INT NOT NULL UNIQUE, -- UM RECEBIVEL POR PEDIDO IMPORTADO
    VALOR_BRUTO NUMERIC(12,2) NOT NULL CHECK (VALOR_BRUTO >= 0),
    TAXAS_PREVISTAS NUMERIC(12,2) NOT NULL DEFAULT 0,
    AJUSTES_PREVISTOS NUMERIC(12,2) NOT NULL DEFAULT 0,
    VALOR_PREVISTO NUMERIC(12,2) NOT NULL CHECK (VALOR_PREVISTO >= 0),
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE TAB_CONTAS_A_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_VENDA
FOREIGN KEY (ID_VENDA) REFERENCES TAB_VENDAS(ID_VENDA);

CREATE TABLE TAB_PARCELAS_A_RECEBER(
    ID_PARCELA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    NUMERO_PARCELA INT NOT NULL CHECK (NUMERO_PARCELA > 0),
    PREVISAO_RECEBIMENTO DATE,
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    UNIQUE (ID_CONTA, NUMERO_PARCELA)
);

ALTER TABLE TAB_PARCELAS_A_RECEBER ADD CONSTRAINT FK_PARCELA_RECEBER_CONTA
FOREIGN KEY (ID_CONTA) REFERENCES TAB_CONTAS_A_RECEBER(ID_CONTA);

CREATE TABLE TAB_REPASSES_PLATAFORMA(
    ID_REPASSE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_LOJA_PLATAFORMA TEXT NOT NULL,
    ID_REPASSE_EXTERNO TEXT, -- PODE NAO EXISTIR NO ARQUIVO DA PLATAFORMA
    PERIODO_INICIO DATE,
    PERIODO_FIM DATE,
    PREVISAO_PAGAMENTO DATE,
    VALOR_LIQUIDO_INFORMADO NUMERIC(12,2),
    STATUS TEXT,
    DATA_IMPORTACAO TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ID_LOJA_PLATAFORMA, ID_REPASSE_EXTERNO)
);

ALTER TABLE TAB_REPASSES_PLATAFORMA ADD CONSTRAINT FK_REPASSE_LOJA_PLATAFORMA
FOREIGN KEY (ID_LOJA_PLATAFORMA) REFERENCES TAB_LOJAS_PLATAFORMAS(ID_LOJA_PLATAFORMA);

CREATE TABLE TAB_REPASSE_RECEBIVEIS(
    ID_REPASSE_RECEBIVEL BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_REPASSE BIGINT NOT NULL,
    ID_CONTA_RECEBER INT NOT NULL,
    VALOR_ATRIBUIDO NUMERIC(12,2) NOT NULL, -- PODE SER NEGATIVO EM AJUSTE/ESTORNO
    UNIQUE (ID_REPASSE, ID_CONTA_RECEBER)
);

ALTER TABLE TAB_REPASSE_RECEBIVEIS ADD CONSTRAINT FK_REPASSE_RECEBIVEL_REPASSE
FOREIGN KEY (ID_REPASSE) REFERENCES TAB_REPASSES_PLATAFORMA(ID_REPASSE);

ALTER TABLE TAB_REPASSE_RECEBIVEIS ADD CONSTRAINT FK_REPASSE_RECEBIVEL_CONTA
FOREIGN KEY (ID_CONTA_RECEBER) REFERENCES TAB_CONTAS_A_RECEBER(ID_CONTA);

CREATE TABLE TAB_CONEXOES_BANCARIAS(
    ID_CONEXAO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROVEDOR TEXT NOT NULL, -- EX.: PLUGGY
    ID_ITEM_EXTERNO TEXT,
    STATUS TEXT,
    EXPIRACAO_CONSENTIMENTO TIMESTAMPTZ,
    ULTIMA_SINCRONIZACAO TIMESTAMPTZ,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (PROVEDOR, ID_ITEM_EXTERNO)
);

CREATE TABLE TAB_CONTAS_BANCARIAS(
    ID_CONTA_BANCARIA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTITUICAO TEXT,
    IDENTIFICACAO TEXT, -- NUMERO/MASCARA; CONTA INTERNA ESTAVEL ENTRE RECONEXOES
    TIPO TEXT,
    STATUS TEXT,
    EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE TAB_CONTAS_BANCARIAS_ORIGENS(
    ID_ORIGEM INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA_BANCARIA INT NOT NULL,
    ID_CONEXAO INT NOT NULL,
    ID_CONTA_EXTERNA TEXT NOT NULL,
    DATA_VINCULO TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ID_CONEXAO, ID_CONTA_EXTERNA),
    UNIQUE (ID_ORIGEM, ID_CONTA_BANCARIA)
);

ALTER TABLE TAB_CONTAS_BANCARIAS_ORIGENS ADD CONSTRAINT FK_ORIGEM_CONTA_BANCARIA
FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TAB_CONTAS_BANCARIAS(ID_CONTA_BANCARIA);

ALTER TABLE TAB_CONTAS_BANCARIAS_ORIGENS ADD CONSTRAINT FK_ORIGEM_CONEXAO
FOREIGN KEY (ID_CONEXAO) REFERENCES TAB_CONEXOES_BANCARIAS(ID_CONEXAO);

CREATE TABLE TAB_TRANSACOES_BANCARIAS(
    ID_TRANSACAO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA_BANCARIA INT NOT NULL,
    ID_ORIGEM INT, -- CONEXAO/CONTA EXTERNA QUE TROUXE O REGISTRO
    ID_TRANSACAO_EXTERNA TEXT,
    ID_PROVEDOR_TRANSACAO TEXT, -- PROVIDERID SE A INTEGRACAO INFORMAR
    DATA_TRANSACAO DATE NOT NULL,
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR <> 0), -- SINAL CONFORME EXTRATO NORMALIZADO
    DESCRICAO TEXT,
    STATUS TEXT NOT NULL, -- PENDENTE, EFETIVADA, ESTORNADA ETC.
    DATA_IMPORTACAO TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ID_ORIGEM, ID_TRANSACAO_EXTERNA)
);

ALTER TABLE TAB_TRANSACOES_BANCARIAS ADD CONSTRAINT FK_TRANSACAO_CONTA_BANCARIA
FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TAB_CONTAS_BANCARIAS(ID_CONTA_BANCARIA);

ALTER TABLE TAB_TRANSACOES_BANCARIAS ADD CONSTRAINT FK_TRANSACAO_ORIGEM
FOREIGN KEY (ID_ORIGEM, ID_CONTA_BANCARIA)
REFERENCES TAB_CONTAS_BANCARIAS_ORIGENS(ID_ORIGEM, ID_CONTA_BANCARIA);

CREATE TABLE TAB_BAIXAS_A_PAGAR(
    ID_BAIXA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PARCELA BIGINT NOT NULL,
    ID_TRANSACAO BIGINT, -- NULO PARA PAGAMENTO MANUAL/FORA DA CONTA PJ
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    DATA_BAIXA DATE NOT NULL,
    ORIGEM TEXT NOT NULL CHECK (ORIGEM IN ('OPEN_FINANCE', 'MANUAL')),
    STATUS TEXT NOT NULL,
    OBSERVACAO TEXT,
    CHECK (ORIGEM <> 'OPEN_FINANCE' OR ID_TRANSACAO IS NOT NULL)
);

ALTER TABLE TAB_BAIXAS_A_PAGAR ADD CONSTRAINT FK_BAIXA_PAGAR_PARCELA
FOREIGN KEY (ID_PARCELA) REFERENCES TAB_PARCELAS_A_PAGAR(ID_PARCELA);

ALTER TABLE TAB_BAIXAS_A_PAGAR ADD CONSTRAINT FK_BAIXA_PAGAR_TRANSACAO
FOREIGN KEY (ID_TRANSACAO) REFERENCES TAB_TRANSACOES_BANCARIAS(ID_TRANSACAO);

CREATE TABLE TAB_BAIXAS_A_RECEBER(
    ID_BAIXA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PARCELA BIGINT NOT NULL,
    ID_TRANSACAO BIGINT, -- UM CREDITO PODE SER DISTRIBUIDO ENTRE VARIOS PEDIDOS
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    DATA_BAIXA DATE NOT NULL,
    ORIGEM TEXT NOT NULL CHECK (ORIGEM IN ('OPEN_FINANCE', 'MANUAL')),
    STATUS TEXT NOT NULL,
    OBSERVACAO TEXT,
    CHECK (ORIGEM <> 'OPEN_FINANCE' OR ID_TRANSACAO IS NOT NULL)
);

ALTER TABLE TAB_BAIXAS_A_RECEBER ADD CONSTRAINT FK_BAIXA_RECEBER_PARCELA
FOREIGN KEY (ID_PARCELA) REFERENCES TAB_PARCELAS_A_RECEBER(ID_PARCELA);

ALTER TABLE TAB_BAIXAS_A_RECEBER ADD CONSTRAINT FK_BAIXA_RECEBER_TRANSACAO
FOREIGN KEY (ID_TRANSACAO) REFERENCES TAB_TRANSACOES_BANCARIAS(ID_TRANSACAO);
