-- FLAME OFFICE: primeiro rascunho do esquema PostgreSQL.
-- Estrutura em revisão; não é uma migração de produção.
-- As tabelas iniciais foram criadas em um esquema de teste isolado no PostgreSQL 17.
-- O bloco financeiro ao final e um rascunho ainda nao executado.
-- Este arquivo não contém dados de negócio nem credenciais.

CREATE TABLE TAB_INSUMOS(
    ID_INSUMO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COD_EXTERNO TEXT, -- CODIGO DA NOTA DE COMPRA
    DESCRICAO TEXT NOT NULL,
    UM_COMPRA TEXT NOT NULL, -- MEDIDA DE COMPRA
    UM_VENDA TEXT NOT NULL, -- MEDIDA DE CONVERSAO PRA VENDA KG > G
    QTDE_COMPRA NUMERIC(10,2) NOT NULL, -- QTD CX
    QTDE_VENDA NUMERIC(10,2) NOT NULL, -- QTD FRAÇÃO
    CUSTO NUMERIC (10,2) NOT NULL, -- CUSTO ATUAL DE COMPRA
    CUSTO_MEDIO NUMERIC (10,2) NOT NULL, -- CALCULADO NA ENTRADA
    CUSTO_VENDA NUMERIC (10,2) NOT NULL, -- CUSTO FRAÇÃO
    CATEGORIA TEXT,
    MARCA TEXT,
    -- ESTOQUE VEM CALCULADO PELO MOV ESTOQUE
    ESTOQUE_MINIMO NUMERIC (10,2) NOT NULL,
    ESTOQUE_RECOMENDADO NUMERIC (10,2) NOT NULL,
    STATUS TEXT,
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE TAB_FORNECEDORES(
    ID_FORNECEDOR INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CNPJ TEXT NOT NULL UNIQUE,
    RAZAO_SOCIAL TEXT NOT NULL,
    FANTASIA TEXT,
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE TAB_USUARIOS(
    ID_USUARIO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME TEXT NOT NULL,
    LOGIN TEXT NOT NULL UNIQUE,
    SENHA_HASH TEXT NOT NULL, -- GERAR O HASH NA APLICACAO; NUNCA GUARDAR SENHA EM TEXTO PURO
    SETOR TEXT NOT NULL CHECK (SETOR IN ('FINANCEIRO', 'ESTOQUE', 'MARKETING', 'GERAL')),
    STATUS TEXT NOT NULL DEFAULT 'ATIVO' CHECK (STATUS IN ('ATIVO', 'INATIVO')),
    DATA_CADASTRO TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE TAB_MOVIMENTO_ESTOQUE(
    ID_MOVIMENTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_INSUMO INT NOT NULL,
    ID_ORIGEM INT,
    QTDE NUMERIC(10,2) NOT NULL,
    ESTOQUE_ANTERIOR NUMERIC(10,2),
    ESTOQUE_POSTERIOR NUMERIC(10,2),
    CUSTO_UNITARIO NUMERIC(10,2) NOT NULL,
    CUSTO_TOTAL NUMERIC(10,2),
    DATA_MOVIMENTO TIMESTAMPTZ DEFAULT NOW(),
    TIPO_MOVIMENTO TEXT,
    MOTIVO_MOVIMENTO TEXT,
    ID_LOJA INT NOT NULL,
    ID_USUARIO INT NOT NULL
);

ALTER TABLE TAB_MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_INSUMO_MOVIMENTO
FOREIGN KEY (ID_INSUMO) REFERENCES TAB_INSUMOS(ID_INSUMO);

ALTER TABLE TAB_MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_USUARIO_MOVIMENTO
FOREIGN KEY (ID_USUARIO) REFERENCES TAB_USUARIOS(ID_USUARIO);

CREATE TABLE TAB_ENTRADAS(
    ID_ENTRADA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL,
    CHAVE_NFE TEXT UNIQUE,
    NUMERO_NFE TEXT,
    VALOR_TOTAL NUMERIC(10,2),
    DATA_ENTRADA TIMESTAMPTZ DEFAULT NOW(),
    STATUS TEXT
);

ALTER TABLE TAB_ENTRADAS ADD CONSTRAINT FK_FORNECEDOR_ENTRADA
FOREIGN KEY (ID_FORNECEDOR) REFERENCES TAB_FORNECEDORES(ID_FORNECEDOR);

CREATE TABLE TAB_ENTRADA_ITENS(
    ID_ITEM BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ENTRADA INT NOT NULL,
    ID_INSUMO INT NOT NULL,
    QTDE_NFE NUMERIC(10,2) NOT NULL,
    UM_COMPRA TEXT,
    UM_ENTRADA TEXT,
    FATOR_CONVERSAO NUMERIC(10,2), -- DEPENDE DA UM_ENTRADA
    QTDE_ENTRADA NUMERIC(10,2) NOT NULL,
    CUSTO_UNITARIO NUMERIC(10,2) NOT NULL,
    SUBTOTAL NUMERIC(10,2) NOT NULL
);

ALTER TABLE TAB_ENTRADA_ITENS ADD CONSTRAINT FK_ENTRADA_INSUMO
FOREIGN KEY (ID_INSUMO) REFERENCES TAB_INSUMOS(ID_INSUMO);

ALTER TABLE TAB_ENTRADA_ITENS ADD CONSTRAINT FK_IDITEM_IDENTRADA
FOREIGN KEY (ID_ENTRADA) REFERENCES TAB_ENTRADAS(ID_ENTRADA);

CREATE TABLE TAB_PRODUTOS ( -- PRODUTO FINAL INDIVIDUAL: LANCHE, PORÇÃO ETC
    ID_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO TEXT UNIQUE NOT NULL,
    CATEGORIA TEXT,
    CMV NUMERIC(10,2),
    PRECO_VENDA NUMERIC(10,2),
    STATUS TEXT
);

CREATE TABLE TAB_PRODUTO_INSUMOS ( -- COMPONENTES DOS PRODUTOS
    ID_INSUMO_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- ID LINHA
    ID_PRODUTO INT NOT NULL, -- ID PRODUTO FINAL
    ID_INSUMO INT NOT NULL, -- ID INSUMO
    QTDE_VENDA NUMERIC(10,2),
    FATOR_USO NUMERIC(10,2),
    CUSTO_UNITARIO NUMERIC (10,2),
    SUBTOTAL NUMERIC (10,2)
);

ALTER TABLE TAB_PRODUTO_INSUMOS ADD CONSTRAINT FK_PRODUTO_INSUMO
FOREIGN KEY (ID_INSUMO) REFERENCES TAB_INSUMOS(ID_INSUMO);

ALTER TABLE TAB_PRODUTO_INSUMOS ADD CONSTRAINT FK_PRODUTO_IDPRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

CREATE TABLE TAB_COMBOS ( -- COMBOS DE PRODUTOS
    ID_COMBO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRICAO TEXT UNIQUE NOT NULL,
    CMV_COMBO NUMERIC(10,2),
    PRECO_VENDA NUMERIC(10,2),
    STATUS TEXT
);

CREATE TABLE TAB_COMBO_PRODUTOS(
    ID_COMBO_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMBO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTDE NUMERIC(10,2) NOT NULL,
    CMV NUMERIC(10,2),
    SUBTOTAL NUMERIC(10,2)
);

ALTER TABLE TAB_COMBO_PRODUTOS ADD CONSTRAINT FK_COMBO_IDCOMBO
FOREIGN KEY (ID_COMBO) REFERENCES TAB_COMBOS(ID_COMBO);

ALTER TABLE TAB_COMBO_PRODUTOS ADD CONSTRAINT FK_COMBO_PRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

CREATE TABLE TAB_LOJAS(
    ID_LOJA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_LOJA TEXT NOT NULL UNIQUE,
    CATEGORIA TEXT,
    STATUS TEXT
);

CREATE TABLE TAB_LOJAS_PLATAFORMAS(
    ID_LOJA_PLATAFORMA TEXT PRIMARY KEY,
    ID_LOJA INT NOT NULL,
    PLATAFORMA TEXT,
    STATUS TEXT
);

ALTER TABLE TAB_LOJAS_PLATAFORMAS ADD CONSTRAINT FK_LOJA_IDLOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

ALTER TABLE TAB_MOVIMENTO_ESTOQUE ADD CONSTRAINT FK_MOVIMENTO_LOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

CREATE TABLE TAB_VENDAS(
    ID_VENDA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA_PLATAFORMA TEXT NOT NULL,
    ID_LOJA INT NOT NULL,
    ID_LOJA_PLATAFORMA TEXT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    HORA_VENDA TIME NOT NULL,
    CUSTO_VENDA NUMERIC(10,2) NOT NULL DEFAULT 0,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL DEFAULT 0,
    DESCONTO_PLATAFORMA NUMERIC(10,2) DEFAULT 0,
    DESCONTO_PAGAMENTO NUMERIC(10,2) DEFAULT 0,
    DESCONTO_ENTREGA NUMERIC(10,2) DEFAULT 0,
    DESCONTO_PROMOCAO NUMERIC(10,2) DEFAULT 0,
    DESCONTO_TOTAL NUMERIC(10,2) DEFAULT 0,
    LUCRO_BRUTO NUMERIC (10,2) DEFAULT 0,
    MARGEM_BRUTA NUMERIC (10,2) DEFAULT 0,
    MARKUP_BRUTO NUMERIC(10,2) DEFAULT 0,
    STATUS TEXT
);

ALTER TABLE TAB_VENDAS ADD CONSTRAINT FK_VENDA_LOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

ALTER TABLE TAB_VENDAS ADD CONSTRAINT FK_VENDA_PLATAFORMA
FOREIGN KEY (ID_LOJA_PLATAFORMA) REFERENCES TAB_LOJAS_PLATAFORMAS(ID_LOJA_PLATAFORMA);

CREATE TABLE TAB_VENDAS_PRODUTOS(
    ID_VENDA_PRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QTDE NUMERIC (10,2) NOT NULL,
    CUSTO NUMERIC (10,2) NOT NULL DEFAULT 0,
    SUBTOTAL NUMERIC(10,2) DEFAULT 0
);

ALTER TABLE TAB_VENDAS_PRODUTOS ADD CONSTRAINT FK_VENDAPRODUTO_IDVENDA
FOREIGN KEY (ID_VENDA) REFERENCES TAB_VENDAS(ID_VENDA);

ALTER TABLE TAB_VENDAS_PRODUTOS ADD CONSTRAINT FK_VENDAPRODUTO_IDPRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

CREATE TABLE TAB_VENDAS_COMPONENTES(
    ID_COMPONENTE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA INT NOT NULL,
    ID_COMBO INT,
    ID_PRODUTO INT,
    QTDE NUMERIC (10,2),
    CUSTO NUMERIC (10,2),
    SUBTOTAL NUMERIC(10,2)
);

ALTER TABLE TAB_VENDAS_COMPONENTES ADD CONSTRAINT FK_COMPONENTE_IDVENDA
FOREIGN KEY (ID_VENDA) REFERENCES TAB_VENDAS(ID_VENDA);

ALTER TABLE TAB_VENDAS_COMPONENTES ADD CONSTRAINT FK_COMPONENTE_IDCOMBO
FOREIGN KEY (ID_COMBO) REFERENCES TAB_COMBOS(ID_COMBO);

ALTER TABLE TAB_VENDAS_COMPONENTES ADD CONSTRAINT FK_COMPONENTE_IDPRODUTO
FOREIGN KEY (ID_PRODUTO) REFERENCES TAB_PRODUTOS(ID_PRODUTO);

-- FINANCEIRO (RASCUNHO): ORIGEM DO TITULO, REPASSE E EXTRATO SAO FATOS DIFERENTES.
-- PENDENTE: RELACIONAR LOJAS E CONTAS BANCARIAS AO CNPJ QUANDO TAB_EMPRESAS FOR DEFINIDA.

CREATE TABLE TAB_CONTAS_A_PAGAR(
    ID_CONTA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_LOJA INT NOT NULL,
    ID_ENTRADA INT UNIQUE, -- PREENCHIDO QUANDO A CONTA NASCE DE UMA NF/ENTRADA
    ORIGEM TEXT NOT NULL CHECK (ORIGEM IN ('NF_ENTRADA', 'MANUAL')),
    BENEFICIARIO TEXT, -- USADO QUANDO NAO HA FORNECEDOR CADASTRADO
    DESCRICAO TEXT NOT NULL,
    CATEGORIA TEXT,
    COMPETENCIA DATE,
    VALOR_TOTAL NUMERIC(12,2) NOT NULL CHECK (VALOR_TOTAL >= 0),
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW(),
    CHECK ((ORIGEM = 'NF_ENTRADA' AND ID_ENTRADA IS NOT NULL)
        OR (ORIGEM = 'MANUAL' AND ID_ENTRADA IS NULL))
);

ALTER TABLE TAB_CONTAS_A_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_LOJA
FOREIGN KEY (ID_LOJA) REFERENCES TAB_LOJAS(ID_LOJA);

ALTER TABLE TAB_CONTAS_A_PAGAR ADD CONSTRAINT FK_CONTA_PAGAR_ENTRADA
FOREIGN KEY (ID_ENTRADA) REFERENCES TAB_ENTRADAS(ID_ENTRADA);

CREATE TABLE TAB_PARCELAS_A_PAGAR(
    ID_PARCELA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    NUMERO_PARCELA INT NOT NULL CHECK (NUMERO_PARCELA > 0),
    VENCIMENTO DATE NOT NULL,
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    UNIQUE (ID_CONTA, NUMERO_PARCELA)
);

ALTER TABLE TAB_PARCELAS_A_PAGAR ADD CONSTRAINT FK_PARCELA_PAGAR_CONTA
FOREIGN KEY (ID_CONTA) REFERENCES TAB_CONTAS_A_PAGAR(ID_CONTA);

CREATE TABLE TAB_CONTAS_A_RECEBER(
    ID_CONTA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VENDA INT NOT NULL UNIQUE, -- UM RECEBIVEL POR PEDIDO IMPORTADO
    VALOR_BRUTO NUMERIC(12,2) NOT NULL CHECK (VALOR_BRUTO >= 0),
    TAXAS_PREVISTAS NUMERIC(12,2) NOT NULL DEFAULT 0,
    AJUSTES_PREVISTOS NUMERIC(12,2) NOT NULL DEFAULT 0,
    VALOR_PREVISTO NUMERIC(12,2) NOT NULL CHECK (VALOR_PREVISTO >= 0),
    DATA_CADASTRO TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE TAB_CONTAS_A_RECEBER ADD CONSTRAINT FK_CONTA_RECEBER_VENDA
FOREIGN KEY (ID_VENDA) REFERENCES TAB_VENDAS(ID_VENDA);

CREATE TABLE TAB_PARCELAS_A_RECEBER(
    ID_PARCELA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    NUMERO_PARCELA INT NOT NULL CHECK (NUMERO_PARCELA > 0),
    PREVISAO_RECEBIMENTO DATE,
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    UNIQUE (ID_CONTA, NUMERO_PARCELA)
);

ALTER TABLE TAB_PARCELAS_A_RECEBER ADD CONSTRAINT FK_PARCELA_RECEBER_CONTA
FOREIGN KEY (ID_CONTA) REFERENCES TAB_CONTAS_A_RECEBER(ID_CONTA);

CREATE TABLE TAB_REPASSES_PLATAFORMA(
    ID_REPASSE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_LOJA_PLATAFORMA TEXT NOT NULL,
    ID_REPASSE_EXTERNO TEXT, -- PODE NAO EXISTIR NO ARQUIVO DA PLATAFORMA
    PERIODO_INICIO DATE,
    PERIODO_FIM DATE,
    PREVISAO_PAGAMENTO DATE,
    VALOR_LIQUIDO_INFORMADO NUMERIC(12,2),
    STATUS TEXT,
    DATA_IMPORTACAO TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ID_LOJA_PLATAFORMA, ID_REPASSE_EXTERNO)
);

ALTER TABLE TAB_REPASSES_PLATAFORMA ADD CONSTRAINT FK_REPASSE_LOJA_PLATAFORMA
FOREIGN KEY (ID_LOJA_PLATAFORMA) REFERENCES TAB_LOJAS_PLATAFORMAS(ID_LOJA_PLATAFORMA);

CREATE TABLE TAB_REPASSE_RECEBIVEIS(
    ID_REPASSE_RECEBIVEL BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_REPASSE BIGINT NOT NULL,
    ID_CONTA_RECEBER INT NOT NULL,
    VALOR_ATRIBUIDO NUMERIC(12,2) NOT NULL, -- PODE SER NEGATIVO EM AJUSTE/ESTORNO
    UNIQUE (ID_REPASSE, ID_CONTA_RECEBER)
);

ALTER TABLE TAB_REPASSE_RECEBIVEIS ADD CONSTRAINT FK_REPASSE_RECEBIVEL_REPASSE
FOREIGN KEY (ID_REPASSE) REFERENCES TAB_REPASSES_PLATAFORMA(ID_REPASSE);

ALTER TABLE TAB_REPASSE_RECEBIVEIS ADD CONSTRAINT FK_REPASSE_RECEBIVEL_CONTA
FOREIGN KEY (ID_CONTA_RECEBER) REFERENCES TAB_CONTAS_A_RECEBER(ID_CONTA);

CREATE TABLE TAB_CONEXOES_BANCARIAS(
    ID_CONEXAO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PROVEDOR TEXT NOT NULL, -- EX.: PLUGGY
    ID_ITEM_EXTERNO TEXT,
    STATUS TEXT,
    EXPIRACAO_CONSENTIMENTO TIMESTAMPTZ,
    ULTIMA_SINCRONIZACAO TIMESTAMPTZ,
    UNIQUE (PROVEDOR, ID_ITEM_EXTERNO)
);

CREATE TABLE TAB_CONTAS_BANCARIAS(
    ID_CONTA_BANCARIA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTITUICAO TEXT,
    IDENTIFICACAO TEXT, -- NUMERO/MASCARA; CONTA INTERNA ESTAVEL ENTRE RECONEXOES
    TIPO TEXT,
    STATUS TEXT
);

CREATE TABLE TAB_CONTAS_BANCARIAS_ORIGENS(
    ID_ORIGEM INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA_BANCARIA INT NOT NULL,
    ID_CONEXAO INT NOT NULL,
    ID_CONTA_EXTERNA TEXT NOT NULL,
    DATA_VINCULO TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ID_CONEXAO, ID_CONTA_EXTERNA),
    UNIQUE (ID_ORIGEM, ID_CONTA_BANCARIA)
);

ALTER TABLE TAB_CONTAS_BANCARIAS_ORIGENS ADD CONSTRAINT FK_ORIGEM_CONTA_BANCARIA
FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TAB_CONTAS_BANCARIAS(ID_CONTA_BANCARIA);

ALTER TABLE TAB_CONTAS_BANCARIAS_ORIGENS ADD CONSTRAINT FK_ORIGEM_CONEXAO
FOREIGN KEY (ID_CONEXAO) REFERENCES TAB_CONEXOES_BANCARIAS(ID_CONEXAO);

CREATE TABLE TAB_TRANSACOES_BANCARIAS(
    ID_TRANSACAO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CONTA_BANCARIA INT NOT NULL,
    ID_ORIGEM INT, -- CONEXAO/CONTA EXTERNA QUE TROUXE O REGISTRO
    ID_TRANSACAO_EXTERNA TEXT,
    ID_PROVEDOR_TRANSACAO TEXT, -- PROVIDERID SE A INTEGRACAO INFORMAR
    DATA_TRANSACAO DATE NOT NULL,
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR <> 0), -- SINAL CONFORME EXTRATO NORMALIZADO
    DESCRICAO TEXT,
    STATUS TEXT NOT NULL, -- PENDENTE, EFETIVADA, ESTORNADA ETC.
    DATA_IMPORTACAO TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (ID_ORIGEM, ID_TRANSACAO_EXTERNA)
);

ALTER TABLE TAB_TRANSACOES_BANCARIAS ADD CONSTRAINT FK_TRANSACAO_CONTA_BANCARIA
FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TAB_CONTAS_BANCARIAS(ID_CONTA_BANCARIA);

ALTER TABLE TAB_TRANSACOES_BANCARIAS ADD CONSTRAINT FK_TRANSACAO_ORIGEM
FOREIGN KEY (ID_ORIGEM, ID_CONTA_BANCARIA)
REFERENCES TAB_CONTAS_BANCARIAS_ORIGENS(ID_ORIGEM, ID_CONTA_BANCARIA);

CREATE TABLE TAB_BAIXAS_A_PAGAR(
    ID_BAIXA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PARCELA BIGINT NOT NULL,
    ID_TRANSACAO BIGINT, -- NULO PARA PAGAMENTO MANUAL/FORA DA CONTA PJ
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    DATA_BAIXA DATE NOT NULL,
    ORIGEM TEXT NOT NULL CHECK (ORIGEM IN ('OPEN_FINANCE', 'MANUAL')),
    STATUS TEXT NOT NULL,
    OBSERVACAO TEXT,
    CHECK (ORIGEM <> 'OPEN_FINANCE' OR ID_TRANSACAO IS NOT NULL)
);

ALTER TABLE TAB_BAIXAS_A_PAGAR ADD CONSTRAINT FK_BAIXA_PAGAR_PARCELA
FOREIGN KEY (ID_PARCELA) REFERENCES TAB_PARCELAS_A_PAGAR(ID_PARCELA);

ALTER TABLE TAB_BAIXAS_A_PAGAR ADD CONSTRAINT FK_BAIXA_PAGAR_TRANSACAO
FOREIGN KEY (ID_TRANSACAO) REFERENCES TAB_TRANSACOES_BANCARIAS(ID_TRANSACAO);

CREATE TABLE TAB_BAIXAS_A_RECEBER(
    ID_BAIXA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PARCELA BIGINT NOT NULL,
    ID_TRANSACAO BIGINT, -- UM CREDITO PODE SER DISTRIBUIDO ENTRE VARIOS PEDIDOS
    VALOR NUMERIC(12,2) NOT NULL CHECK (VALOR > 0),
    DATA_BAIXA DATE NOT NULL,
    ORIGEM TEXT NOT NULL CHECK (ORIGEM IN ('OPEN_FINANCE', 'MANUAL')),
    STATUS TEXT NOT NULL,
    OBSERVACAO TEXT,
    CHECK (ORIGEM <> 'OPEN_FINANCE' OR ID_TRANSACAO IS NOT NULL)
);

ALTER TABLE TAB_BAIXAS_A_RECEBER ADD CONSTRAINT FK_BAIXA_RECEBER_PARCELA
FOREIGN KEY (ID_PARCELA) REFERENCES TAB_PARCELAS_A_RECEBER(ID_PARCELA);

ALTER TABLE TAB_BAIXAS_A_RECEBER ADD CONSTRAINT FK_BAIXA_RECEBER_TRANSACAO
FOREIGN KEY (ID_TRANSACAO) REFERENCES TAB_TRANSACOES_BANCARIAS(ID_TRANSACAO);
